### ISSUE TITLE
Recursive link in 'Feedback / Contributing' section of README.md 

### ISSUE THREAD

**Issue by kevjonesin** [fboender/gexec#1]
@fboender 
At present, the link _[https://bitbucket.org/fboender/gexec/](https://bitbucket.org/fboender/gexec/)_ in the ['Feedback / Contributing' section of README.md](https://github.com/fboender/gexec#feedback--contributing) points to a defunct page with a link back to this the originating site, _[https://github.com/fboender/gexec](https://github.com/fboender/gexec)_, thus making a recursive loop. Perhaps it might be reworded to direct to relevant tabs here on GitHub?

**Comment by fboender** [comment]
Thanks for the tip! I've fixed this in the latest master branch. I also fixed the screenshots link.
